-- Set Primary Keys
ALTER TABLE dbo.Ball ADD CONSTRAINT PK_Ball PRIMARY KEY (DrawingId, BallPlace);
ALTER TABLE dbo.BallType ADD CONSTRAINT PK_BallType PRIMARY KEY (BallTypeId);
ALTER TABLE dbo.Drawing ADD CONSTRAINT PK_Drawing PRIMARY KEY (DrawingId);
ALTER TABLE dbo.Lotto ADD CONSTRAINT PK_Lotto PRIMARY KEY (LottoId);
ALTER TABLE dbo.LottoState ADD CONSTRAINT PK_LottoState PRIMARY KEY (LottoId, StateId);
ALTER TABLE dbo.Odds ADD CONSTRAINT PK_Odds PRIMARY KEY (OddsId);
ALTER TABLE dbo.State ADD CONSTRAINT PK_State PRIMARY KEY (StateId);

-- Set Foreign Keys
ALTER TABLE dbo.LottoState ADD CONSTRAINT FK_LOTTOSTATE_LOTTOID FOREIGN KEY(LottoId) REFERENCES dbo.Lotto(LottoId);
ALTER TABLE dbo.LottoState ADD CONSTRAINT FK_LOTTOSTATE_STATEID FOREIGN KEY(StateId) REFERENCES dbo.State(StateId);
ALTER TABLE dbo.Odds ADD CONSTRAINT FK_ODDS_LOTTOID FOREIGN KEY(LottoId) REFERENCES dbo.Lotto(LottoId);
ALTER TABLE dbo.Drawing ADD CONSTRAINT FK_DRAWING_LOTTOID FOREIGN KEY(LottoId) REFERENCES dbo.Lotto(LottoId);
ALTER TABLE dbo.Ball ADD CONSTRAINT FK_BALL_DRAWINGID FOREIGN KEY(DrawingId) REFERENCES dbo.Drawing(DrawingId);
ALTER TABLE dbo.Ball ADD CONSTRAINT FK_BALL_BALLTYPE FOREIGN KEY(BallTypeId) REFERENCES dbo.BallType(BallTypeId); 